### ISSUE TITLE
Profile type bug

### ISSUE THREAD

**Issue by emieza** [AWS2/djmatrics#13]
Profile_type ha d'estar  traduit correctament.

Ha de tenir 3 possibles valors (ara en té 2):

- obligatori
- exempció
- bonificació del 50%

**Comment by edusnchezj** [comment]
Se ha hecho el cambio en los **modelos** con el siguiente código:
```
class ProfileRequirement(models.Model):
    class Meta:
        verbose_name = "Perfil de requeriments"
        verbose_name_plural = "Perfils de requeriment"

    class ProfileChoices(Enum):
        OB = 'obligatori'
        EX = 'exempció'
        BO = 'bonificació del 50%'

    name = models.CharField("nom", max_length=255)
    description = models.TextField("descripció", null=True)
    profile_type = models.CharField('profile_type', max_length=9, choices=[(val_state, val_state.value) for val_state in ProfileChoices], default=None, null=False)
```
Por parte de los **factories**:

```profile_type = lazy_attribute(lambda x: fake.random_element(elements=('obligatori', 'exempció', 'bonificació del 50%')))```

**Comment by edusnchezj** [comment]
**Es necesario arreglar los perfiles en `/student/profiles` al realizar este cambio.**
