### ISSUE TITLE
EnrolmentUF object can be changed by a ManyToMany relationship

### ISSUE THREAD

**Issue by emieza** [AWS2/djmatrics#3]
- [x] In order to enable an student to select their UFs, the EnrolmentUF object works, but it would be more easy to integrate and use a [ManyToMany relationship](https://docs.djangoproject.com/en/3.2/topics/db/examples/many_to_many/)  between Enrolment and UF object.

**Comment by rbnmf** [comment]
Should be done now https://github.com/AWS2/djmatrics/commit/4ab191dcb40a0f90dffb7e90837b085d6e4dacf5 @emieza
