### ISSUE TITLE
Image privacy

### ISSUE THREAD

**Issue by emieza** [AWS2/djmatrics#6]
in order to keep image privacy (they are private docs), they will only be displayed embedded into the HTML or in the API.

So, the Upload model can use a standard ImageField, upload to the standard filesystem, and then [access the image file binary data as in this example](https://www.codegrepper.com/code-examples/python/send+image+bytes+python+base64+string) (remember to access the image file as `obj.image.path`, and then [render the image embedded as here](https://www.w3docs.com/snippets/html/how-to-display-base64-images-in-html.html).

This way Django will be able to control which files are available for each user, instead of serving them as static content.

The API will be able to send this image as well in a similar way, streaming in base64

It has only the drawback of not being something able to be cached, and thus will be less efficient (but secure which is a must).

**Comment by rbnmf** [comment]
Closed. See #2
